# Generated by Django 5.0.6 on 2024-10-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='payment_method',
            field=models.CharField(choices=[('Upi', 'Upi'), ('Cash', 'Cash')], default='Upi', max_length=100),
        ),
    ]
